[DB]
	host = 'localhost'
	port = 3306
	user = 'vajnar'
	password = 'AldebaraN7#'
	database = 'pp_oftake'

[DB41]
	ODBCDNS=mysql41
	#ODBCDNS=mysql41local

[API]
	#okolje je lahko (TEST,PROD)
	okolje = PROD


	# URL PRODUKCIJE
	baseUrl = https://pp.plinovodi.si/PpApi
	# URL TESTIRANJE
	baseUrlTest = https://pp-test.plinovodi.si/PpApi

[CERT]
	cert_file = WSEnos2025.crt
	key_file = WSEnos2025.key
