[DB]
	host = 192.168.7.40
	port = 3306
	user = ewon
	password = EewonE
	database = generalna

[DB41]
	ODBCDNS=mysql41
	#ODBCDNS=mysql41local

[API]
	#okolje je lahko (TEST,PROD)
	okolje = TEST


	# URL PRODUKCIJE
	baseUrl = https://pp.plinovodi.si/PpApi
	# URL TESTIRANJE
	baseUrlTest = https://pp-test.plinovodi.si/PpApi

[CERT]
	cert_file = WSEnos2025.crt
	key_file = WSEnos2025.key
